import type { QuizQuestion } from '@/types';

const Q: QuizQuestion[] = [
  { id: 'eng-01', subject: 'anglais', emoji: '🇬🇧', question: 'What is the English translation of "chat" ?', options: [{ id: 'A', text: 'Dog' }, { id: 'B', text: 'Cat' }, { id: 'C', text: 'Bird' }, { id: 'D', text: 'Fish' }], correctOptionId: 'B', explanation: '"Chat" en français = "Cat" en anglais. A cat says meow!', difficulty: 1, xpReward: 10 },
  { id: 'eng-02', subject: 'anglais', emoji: '🔢', question: 'How do you say "bonjour" in English ?', options: [{ id: 'A', text: 'Goodbye' }, { id: 'B', text: 'Please' }, { id: 'C', text: 'Hello' }, { id: 'D', text: 'Thank you' }], correctOptionId: 'C', explanation: '"Bonjour" = "Hello" in English. Good morning is also used in the morning.', difficulty: 1, xpReward: 10 },
  { id: 'eng-03', subject: 'anglais', emoji: '🌈', question: 'Which word means "rouge" in English ?', options: [{ id: 'A', text: 'Blue' }, { id: 'B', text: 'Green' }, { id: 'C', text: 'Yellow' }, { id: 'D', text: 'Red' }], correctOptionId: 'D', explanation: '"Rouge" = "Red" in English. The red colour!', difficulty: 1, xpReward: 10 },
  { id: 'eng-04', subject: 'anglais', emoji: '📅', question: 'What day comes after "Monday" ?', options: [{ id: 'A', text: 'Sunday' }, { id: 'B', text: 'Tuesday' }, { id: 'C', text: 'Wednesday' }, { id: 'D', text: 'Saturday' }], correctOptionId: 'B', explanation: 'The days: Monday, Tuesday, Wednesday, Thursday, Friday, Saturday, Sunday.', difficulty: 1, xpReward: 10 },
  { id: 'eng-05', subject: 'anglais', emoji: '🔢', question: 'How do you say "vingt" (20) in English ?', options: [{ id: 'A', text: 'Twelve' }, { id: 'B', text: 'Fifteen' }, { id: 'C', text: 'Twenty' }, { id: 'D', text: 'Thirty' }], correctOptionId: 'C', explanation: '20 = Twenty. Autres : 10 = ten, 15 = fifteen, 30 = thirty.', difficulty: 1, xpReward: 10 },
  { id: 'eng-06', subject: 'anglais', emoji: '👨‍👩‍👧', question: 'What is the English word for "famille" ?', options: [{ id: 'A', text: 'Friend' }, { id: 'B', text: 'Family' }, { id: 'C', text: 'School' }, { id: 'D', text: 'Home' }], correctOptionId: 'B', explanation: '"Famille" = "Family" in English. My family: mother, father, sister, brother.', difficulty: 1, xpReward: 10 },
  { id: 'eng-07', subject: 'anglais', emoji: '🐕', question: 'Complete: "I ___ a dog." (avoir)', options: [{ id: 'A', text: 'is' }, { id: 'B', text: 'am' }, { id: 'C', text: 'have' }, { id: 'D', text: 'has' }], correctOptionId: 'C', explanation: 'I have = j\'ai. She has, he has. I am = je suis.', difficulty: 2, xpReward: 15 },
  { id: 'eng-08', subject: 'anglais', emoji: '🌍', question: 'What is the capital of England ?', options: [{ id: 'A', text: 'Manchester' }, { id: 'B', text: 'Edinburgh' }, { id: 'C', text: 'London' }, { id: 'D', text: 'Birmingham' }], correctOptionId: 'C', explanation: 'London (Londres) is the capital of England and the United Kingdom.', difficulty: 1, xpReward: 10 },
  { id: 'eng-09', subject: 'anglais', emoji: '🌡️', question: 'What does "hot" mean in French ?', options: [{ id: 'A', text: 'Froid' }, { id: 'B', text: 'Mouillé' }, { id: 'C', text: 'Chaud' }, { id: 'D', text: 'Beau' }], correctOptionId: 'C', explanation: '"Hot" = chaud. "Cold" = froid. "Warm" = tiède.', difficulty: 1, xpReward: 10 },
];

export default Q;
