import type { QuizQuestion } from '@/types';

const Q: QuizQuestion[] = [
  { id: 'chi-01', subject: 'chimie', emoji: '⚗️', question: 'Quelle est la formule chimique de l\'eau ?', options: [{ id: 'A', text: 'H₂O' }, { id: 'B', text: 'CO₂' }, { id: 'C', text: 'NaCl' }, { id: 'D', text: 'O₂' }], correctOptionId: 'A', explanation: 'L\'eau est composée de 2 atomes d\'hydrogène (H) et 1 atome d\'oxygène (O).', difficulty: 1, xpReward: 10 },
  { id: 'chi-02', subject: 'chimie', emoji: '🔥', question: 'Quel gaz est indispensable à la combustion ?', options: [{ id: 'A', text: 'Azote (N₂)' }, { id: 'B', text: 'Dioxyde de carbone (CO₂)' }, { id: 'C', text: 'Oxygène (O₂)' }, { id: 'D', text: 'Hydrogène (H₂)' }], correctOptionId: 'C', explanation: 'La combustion nécessite de l\'oxygène. Sans O₂, le feu s\'éteint.', difficulty: 1, xpReward: 10 },
  { id: 'chi-03', subject: 'chimie', emoji: '🧂', question: 'Quelle est la formule du sel de table (chlorure de sodium) ?', options: [{ id: 'A', text: 'KCl' }, { id: 'B', text: 'NaCl' }, { id: 'C', text: 'CaCl₂' }, { id: 'D', text: 'MgO' }], correctOptionId: 'B', explanation: 'Le sel de table est NaCl : sodium (Na) + chlore (Cl).', difficulty: 2, xpReward: 15 },
  { id: 'chi-04', subject: 'chimie', emoji: '⚛️', question: 'Combien de protons possède un atome d\'hydrogène ?', options: [{ id: 'A', text: '0' }, { id: 'B', text: '1' }, { id: 'C', text: '2' }, { id: 'D', text: '6' }], correctOptionId: 'B', explanation: 'L\'hydrogène est le plus simple : 1 proton, 1 électron, numéro atomique 1.', difficulty: 2, xpReward: 15 },
  { id: 'chi-05', subject: 'chimie', emoji: '🌡️', question: 'Que se passe-t-il lors d\'une réaction exothermique ?', options: [{ id: 'A', text: 'Elle absorbe de la chaleur' }, { id: 'B', text: 'Elle libère de la chaleur' }, { id: 'C', text: 'La température reste stable' }, { id: 'D', text: 'Elle produit de la lumière uniquement' }], correctOptionId: 'B', explanation: 'Exo = vers l\'extérieur. Une réaction exothermique dégage de la chaleur.', difficulty: 2, xpReward: 15 },
  { id: 'chi-06', subject: 'chimie', emoji: '🧪', question: 'Le pH 7 correspond à quel type de solution ?', options: [{ id: 'A', text: 'Acide' }, { id: 'B', text: 'Basique' }, { id: 'C', text: 'Neutre' }, { id: 'D', text: 'Corrosive' }], correctOptionId: 'C', explanation: 'pH 7 = neutre (eau pure). pH < 7 = acide. pH > 7 = basique.', difficulty: 2, xpReward: 15 },
  { id: 'chi-07', subject: 'chimie', emoji: '💎', question: 'Le diamant est composé de quel élément ?', options: [{ id: 'A', text: 'Silicium' }, { id: 'B', text: 'Carbone' }, { id: 'C', text: 'Aluminium' }, { id: 'D', text: 'Calcium' }], correctOptionId: 'B', explanation: 'Le diamant est du carbone pur sous forme cristalline. Comme le graphite du crayon !', difficulty: 2, xpReward: 15 },
  { id: 'chi-08', subject: 'chimie', emoji: '🫧', question: 'Que produit la réaction entre le vinaigre et le bicarbonate de soude ?', options: [{ id: 'A', text: 'De l\'eau uniquement' }, { id: 'B', text: 'Du gaz (CO₂)' }, { id: 'C', text: 'De l\'huile' }, { id: 'D', text: 'De l\'alcool' }], correctOptionId: 'B', explanation: 'Cette réaction produit du dioxyde de carbone (CO₂) : les bulles que tu vois !', difficulty: 1, xpReward: 10 },
];

export default Q;
