import type { QuizQuestion } from '@/types';

const Q: QuizQuestion[] = [
  { id: 'esp-01', subject: 'espace', emoji: '🌍', question: 'Quelle planète est la troisième à partir du Soleil ?', options: [{ id: 'A', text: 'Mars' }, { id: 'B', text: 'Vénus' }, { id: 'C', text: 'Terre' }, { id: 'D', text: 'Mercure' }], correctOptionId: 'C', explanation: 'La Terre est la 3ème planète. Ordre : Mercure, Vénus, Terre, Mars...', difficulty: 1, xpReward: 10 },
  { id: 'esp-02', subject: 'espace', emoji: '☀️', question: 'Combien de temps la lumière du Soleil met-elle pour atteindre la Terre ?', options: [{ id: 'A', text: '1 seconde' }, { id: 'B', text: '8 minutes' }, { id: 'C', text: '1 heure' }, { id: 'D', text: '1 jour' }], correctOptionId: 'B', explanation: 'La lumière parcourt 150 millions de km en environ 8 minutes.', difficulty: 2, xpReward: 15 },
  { id: 'esp-03', subject: 'espace', emoji: '🌕', question: 'Quelle est la durée d\'une révolution de la Lune autour de la Terre ?', options: [{ id: 'A', text: '7 jours' }, { id: 'B', text: '14 jours' }, { id: 'C', text: '28 jours' }, { id: 'D', text: '365 jours' }], correctOptionId: 'C', explanation: 'La Lune tourne autour de la Terre en environ 28 jours (un mois lunaire).', difficulty: 1, xpReward: 10 },
  { id: 'esp-04', subject: 'espace', emoji: '🪐', question: 'Quelle est la plus grande planète du système solaire ?', options: [{ id: 'A', text: 'Saturne' }, { id: 'B', text: 'Neptune' }, { id: 'C', text: 'Uranus' }, { id: 'D', text: 'Jupiter' }], correctOptionId: 'D', explanation: 'Jupiter est la plus grande : 1 300 Terres rentreraient dedans !', difficulty: 1, xpReward: 10 },
  { id: 'esp-05', subject: 'espace', emoji: '⭐', question: 'Comment appelle-t-on une étoile mourante qui explose violemment ?', options: [{ id: 'A', text: 'Nébuleuse' }, { id: 'B', text: 'Supernova' }, { id: 'C', text: 'Pulsar' }, { id: 'D', text: 'Quasar' }], correctOptionId: 'B', explanation: 'Une supernova est l\'explosion d\'une étoile massive en fin de vie.', difficulty: 2, xpReward: 15 },
  { id: 'esp-06', subject: 'espace', emoji: '🚀', question: 'En quelle année Neil Armstrong a-t-il marché sur la Lune ?', options: [{ id: 'A', text: '1961' }, { id: 'B', text: '1965' }, { id: 'C', text: '1969' }, { id: 'D', text: '1972' }], correctOptionId: 'C', explanation: 'Apollo 11 a atterri sur la Lune le 20 juillet 1969.', difficulty: 2, xpReward: 15 },
  { id: 'esp-07', subject: 'espace', emoji: '🌌', question: 'Quel est le nom de notre galaxie ?', options: [{ id: 'A', text: 'Andromède' }, { id: 'B', text: 'La Voie Lactée' }, { id: 'C', text: 'Le Grand Nuage' }, { id: 'D', text: 'Messier 87' }], correctOptionId: 'B', explanation: 'Nous vivons dans la Voie Lactée, une galaxie spirale d\'environ 200 milliards d\'étoiles.', difficulty: 1, xpReward: 10 },
  { id: 'esp-08', subject: 'espace', emoji: '🌑', question: 'Qu\'est-ce qu\'une éclipse solaire totale ?', options: [{ id: 'A', text: 'La Terre passe devant le Soleil' }, { id: 'B', text: 'La Lune passe devant le Soleil' }, { id: 'C', text: 'Le Soleil s\'éteint' }, { id: 'D', text: 'La Lune disparaît' }], correctOptionId: 'B', explanation: 'La Lune se place entre la Terre et le Soleil et masque complètement le Soleil.', difficulty: 2, xpReward: 15 },
  { id: 'esp-09', subject: 'espace', emoji: '🌠', question: 'Comment appelle-t-on les "étoiles filantes" ?', options: [{ id: 'A', text: 'Astéroïdes' }, { id: 'B', text: 'Comètes' }, { id: 'C', text: 'Météores' }, { id: 'D', text: 'Satellites' }], correctOptionId: 'C', explanation: 'Les météores sont des fragments de roche qui brûlent dans l\'atmosphère.', difficulty: 2, xpReward: 15 },
  { id: 'esp-10', subject: 'espace', emoji: '🌞', question: 'Le Soleil est principalement composé de quel gaz ?', options: [{ id: 'A', text: 'Oxygène' }, { id: 'B', text: 'Hélium' }, { id: 'C', text: 'Hydrogène' }, { id: 'D', text: 'Azote' }], correctOptionId: 'C', explanation: 'Le Soleil est composé à 73 % d\'hydrogène et à 25 % d\'hélium.', difficulty: 2, xpReward: 15 },
];

export default Q;
