import type { QuizQuestion } from '@/types';

const Q: QuizQuestion[] = [
  { id: 'esp-es-01', subject: 'espagnol', emoji: '🇪🇸', question: 'Comment dit-on "bonjour" en espagnol ?', options: [{ id: 'A', text: 'Buenas noches' }, { id: 'B', text: 'Hola' }, { id: 'C', text: 'Adiós' }, { id: 'D', text: 'Gracias' }], correctOptionId: 'B', explanation: '"Hola" = bonjour. "Buenos días" = bonjour (matin). "Adiós" = au revoir.', difficulty: 1, xpReward: 10 },
  { id: 'esp-es-02', subject: 'espagnol', emoji: '🔢', question: 'Comment dit-on "trois" en espagnol ?', options: [{ id: 'A', text: 'Uno' }, { id: 'B', text: 'Dos' }, { id: 'C', text: 'Tres' }, { id: 'D', text: 'Cuatro' }], correctOptionId: 'C', explanation: 'Les chiffres : uno (1), dos (2), tres (3), cuatro (4), cinco (5).', difficulty: 1, xpReward: 10 },
  { id: 'esp-es-03', subject: 'espagnol', emoji: '🐱', question: 'Que signifie "el gato" en français ?', options: [{ id: 'A', text: 'Le chien' }, { id: 'B', text: 'Le chat' }, { id: 'C', text: 'Le lapin' }, { id: 'D', text: 'Le cheval' }], correctOptionId: 'B', explanation: '"El gato" = le chat. "El perro" = le chien. "El caballo" = le cheval.', difficulty: 1, xpReward: 10 },
  { id: 'esp-es-04', subject: 'espagnol', emoji: '🌞', question: 'Que signifie "hace calor" ?', options: [{ id: 'A', text: 'Il fait froid' }, { id: 'B', text: 'Il pleut' }, { id: 'C', text: 'Il fait chaud' }, { id: 'D', text: 'Il vente' }], correctOptionId: 'C', explanation: '"Hace calor" = il fait chaud. "Hace frío" = il fait froid.', difficulty: 2, xpReward: 15 },
  { id: 'esp-es-05', subject: 'espagnol', emoji: '👨‍👩‍👧', question: 'Comment dit-on "mère" en espagnol ?', options: [{ id: 'A', text: 'Padre' }, { id: 'B', text: 'Hermano' }, { id: 'C', text: 'Madre' }, { id: 'D', text: 'Abuelo' }], correctOptionId: 'C', explanation: '"Madre" = mère, "padre" = père, "hermano" = frère, "abuelo" = grand-père.', difficulty: 1, xpReward: 10 },
  { id: 'esp-es-06', subject: 'espagnol', emoji: '🇪🇸', question: 'Quelle est la capitale de l\'Espagne ?', options: [{ id: 'A', text: 'Barcelone' }, { id: 'B', text: 'Séville' }, { id: 'C', text: 'Valence' }, { id: 'D', text: 'Madrid' }], correctOptionId: 'D', explanation: 'Madrid (Madrí en espagnol) est la capitale de l\'Espagne.', difficulty: 1, xpReward: 10 },
  { id: 'esp-es-07', subject: 'espagnol', emoji: '🎨', question: 'Que signifie "rojo" en français ?', options: [{ id: 'A', text: 'Bleu' }, { id: 'B', text: 'Vert' }, { id: 'C', text: 'Rouge' }, { id: 'D', text: 'Jaune' }], correctOptionId: 'C', explanation: '"Rojo" = rouge. "Azul" = bleu. "Verde" = vert. "Amarillo" = jaune.', difficulty: 1, xpReward: 10 },
  { id: 'esp-es-08', subject: 'espagnol', emoji: '🏠', question: 'Comment dit-on "maison" en espagnol ?', options: [{ id: 'A', text: 'Escuela' }, { id: 'B', text: 'Casa' }, { id: 'C', text: 'Ciudad' }, { id: 'D', text: 'Calle' }], correctOptionId: 'B', explanation: '"La casa" = la maison. "La escuela" = l\'école. "La calle" = la rue.', difficulty: 1, xpReward: 10 },
];

export default Q;
