import type { QuizQuestion } from '@/types';

const Q: QuizQuestion[] = [
  { id: 'geo-01', subject: 'geo', emoji: '🗼', question: 'Quelle est la capitale de la France ?', options: [{ id: 'A', text: 'Lyon' }, { id: 'B', text: 'Marseille' }, { id: 'C', text: 'Paris' }, { id: 'D', text: 'Bordeaux' }], correctOptionId: 'C', explanation: 'Paris est la capitale de la France depuis des siècles.', difficulty: 1, xpReward: 5 },
  { id: 'geo-02', subject: 'geo', emoji: '🌍', question: 'Combien y a-t-il de continents sur Terre ?', options: [{ id: 'A', text: '5' }, { id: 'B', text: '6' }, { id: 'C', text: '7' }, { id: 'D', text: '8' }], correctOptionId: 'C', explanation: '7 continents : Afrique, Antarctique, Asie, Europe, Amérique du Nord, Amérique du Sud, Océanie.', difficulty: 1, xpReward: 10 },
  { id: 'geo-03', subject: 'geo', emoji: '🏔️', question: 'Quel est le plus haut sommet du monde ?', options: [{ id: 'A', text: 'Mont Blanc' }, { id: 'B', text: 'K2' }, { id: 'C', text: 'Kilimandjaro' }, { id: 'D', text: 'L\'Everest' }], correctOptionId: 'D', explanation: 'L\'Everest culmine à 8 849 m dans l\'Himalaya, à la frontière Népal-Chine.', difficulty: 1, xpReward: 10 },
  { id: 'geo-04', subject: 'geo', emoji: '🌊', question: 'Quel est le plus grand océan du monde ?', options: [{ id: 'A', text: 'Atlantique' }, { id: 'B', text: 'Indien' }, { id: 'C', text: 'Arctique' }, { id: 'D', text: 'Pacifique' }], correctOptionId: 'D', explanation: 'Le Pacifique couvre plus de 165 millions de km², soit 1/3 de la surface terrestre.', difficulty: 1, xpReward: 10 },
  { id: 'geo-05', subject: 'geo', emoji: '🇯🇵', question: 'Quelle est la capitale du Japon ?', options: [{ id: 'A', text: 'Séoul' }, { id: 'B', text: 'Pékin' }, { id: 'C', text: 'Tokyo' }, { id: 'D', text: 'Osaka' }], correctOptionId: 'C', explanation: 'Tokyo est la capitale du Japon, avec plus de 37 millions d\'habitants dans l\'agglomération.', difficulty: 1, xpReward: 10 },
  { id: 'geo-06', subject: 'geo', emoji: '🌎', question: 'Quel est le plus long fleuve du monde ?', options: [{ id: 'A', text: 'Amazone' }, { id: 'B', text: 'Mississippi' }, { id: 'C', text: 'Yangtsé' }, { id: 'D', text: 'Nil' }], correctOptionId: 'D', explanation: 'Le Nil mesure environ 6 650 km, légèrement plus long que l\'Amazone.', difficulty: 2, xpReward: 15 },
  { id: 'geo-07', subject: 'geo', emoji: '🏜️', question: 'Quel est le plus grand désert du monde ?', options: [{ id: 'A', text: 'Sahara' }, { id: 'B', text: 'Gobi' }, { id: 'C', text: 'Antarctique' }, { id: 'D', text: 'Arabie' }], correctOptionId: 'C', explanation: 'L\'Antarctique (désert froid) est le plus grand désert avec 14 millions de km².', difficulty: 3, xpReward: 20 },
  { id: 'geo-08', subject: 'geo', emoji: '🇧🇷', question: 'Quelle est la capitale du Brésil ?', options: [{ id: 'A', text: 'São Paulo' }, { id: 'B', text: 'Rio de Janeiro' }, { id: 'C', text: 'Brasília' }, { id: 'D', text: 'Salvador' }], correctOptionId: 'C', explanation: 'Brasília est la capitale fédérale du Brésil, construite de toutes pièces en 1960.', difficulty: 2, xpReward: 15 },
  { id: 'geo-09', subject: 'geo', emoji: '🌐', question: 'Sur combien de fuseaux horaires la Terre est-elle divisée ?', options: [{ id: 'A', text: '12' }, { id: 'B', text: '24' }, { id: 'C', text: '36' }, { id: 'D', text: '48' }], correctOptionId: 'B', explanation: 'La Terre a 24 fuseaux horaires, un par heure (360° ÷ 15° = 24).', difficulty: 2, xpReward: 15 },
];

export default Q;
