import type { QuizQuestion } from '@/types';

const Q: QuizQuestion[] = [
  { id: 'info-01', subject: 'informatique', emoji: '💻', question: 'Qu\'est-ce qu\'un algorithme ?', options: [{ id: 'A', text: 'Un logiciel payant' }, { id: 'B', text: 'Une suite d\'instructions pour résoudre un problème' }, { id: 'C', text: 'Un type de processeur' }, { id: 'D', text: 'Un langage de programmation' }], correctOptionId: 'B', explanation: 'Un algorithme est une suite finie d\'instructions pour résoudre un problème donné.', difficulty: 1, xpReward: 10 },
  { id: 'info-02', subject: 'informatique', emoji: '🔢', question: 'En base binaire, comment s\'écrit le nombre 5 ?', options: [{ id: 'A', text: '101' }, { id: 'B', text: '110' }, { id: 'C', text: '011' }, { id: 'D', text: '100' }], correctOptionId: 'A', explanation: '5 en binaire = 101 (1×4 + 0×2 + 1×1 = 5). Le binaire n\'utilise que 0 et 1.', difficulty: 2, xpReward: 15 },
  { id: 'info-03', subject: 'informatique', emoji: '🌐', question: 'Que signifie "HTTP" dans une adresse web ?', options: [{ id: 'A', text: 'High Tech Transfer Protocol' }, { id: 'B', text: 'HyperText Transfer Protocol' }, { id: 'C', text: 'Home Transfer Text Protocol' }, { id: 'D', text: 'Hyper Transfer Text Program' }], correctOptionId: 'B', explanation: 'HTTP = HyperText Transfer Protocol. HTTPS est la version sécurisée (avec chiffrement).', difficulty: 2, xpReward: 15 },
  { id: 'info-04', subject: 'informatique', emoji: '🖥️', question: 'Quel composant est appelé le "cerveau" de l\'ordinateur ?', options: [{ id: 'A', text: 'RAM' }, { id: 'B', text: 'Disque dur' }, { id: 'C', text: 'Processeur (CPU)' }, { id: 'D', text: 'Carte graphique' }], correctOptionId: 'C', explanation: 'Le CPU (Central Processing Unit) exécute les instructions. Plus il est rapide, plus l\'ordi est puissant.', difficulty: 1, xpReward: 10 },
  { id: 'info-05', subject: 'informatique', emoji: '📦', question: 'Que signifie "RAM" ?', options: [{ id: 'A', text: 'Random Access Memory' }, { id: 'B', text: 'Read And Modify' }, { id: 'C', text: 'Rapid Application Module' }, { id: 'D', text: 'Remote Access Mode' }], correctOptionId: 'A', explanation: 'RAM = Random Access Memory. C\'est la mémoire vive, rapide mais volatile (s\'efface à l\'extinction).', difficulty: 2, xpReward: 15 },
  { id: 'info-06', subject: 'informatique', emoji: '🔐', question: 'Un "bug" en informatique, c\'est quoi ?', options: [{ id: 'A', text: 'Un virus' }, { id: 'B', text: 'Une erreur dans le code' }, { id: 'C', text: 'Un fichier corrompu' }, { id: 'D', text: 'Un réseau lent' }], correctOptionId: 'B', explanation: 'Bug = erreur dans un programme. Le terme vient d\'un vrai insecte trouvé dans un ordinateur en 1947 !', difficulty: 1, xpReward: 10 },
  { id: 'info-07', subject: 'informatique', emoji: '🗃️', question: 'Quelle extension de fichier est typique d\'une image ?', options: [{ id: 'A', text: '.mp3' }, { id: 'B', text: '.pdf' }, { id: 'C', text: '.jpg' }, { id: 'D', text: '.exe' }], correctOptionId: 'C', explanation: '.jpg (et .png, .gif) = images. .mp3 = audio. .pdf = document. .exe = programme Windows.', difficulty: 1, xpReward: 10 },
  { id: 'info-08', subject: 'informatique', emoji: '🌍', question: 'Qu\'est-ce qu\'IP dans "adresse IP" ?', options: [{ id: 'A', text: 'Internet Protocol' }, { id: 'B', text: 'Internal Port' }, { id: 'C', text: 'Integrated Program' }, { id: 'D', text: 'Internet Password' }], correctOptionId: 'A', explanation: 'IP = Internet Protocol. Chaque appareil sur Internet a une adresse IP unique (ex: 192.168.0.1).', difficulty: 2, xpReward: 15 },
];

export default Q;
