import type { QuizQuestion } from '@/types';

const Q: QuizQuestion[] = [
  { id: 'mec-01', subject: 'mecanique', emoji: '⚙️', question: 'Quelle est la loi de Newton en mécanique classique ?', options: [{ id: 'A', text: 'F = mc²' }, { id: 'B', text: 'F = m × a' }, { id: 'C', text: 'F = m / a' }, { id: 'D', text: 'F = a / m' }], correctOptionId: 'B', explanation: 'F = m × a : la force est égale à la masse multipliée par l\'accélération (2ème loi de Newton).', difficulty: 2, xpReward: 15 },
  { id: 'mec-02', subject: 'mecanique', emoji: '🔧', question: 'Quelle est l\'unité de mesure de la force ?', options: [{ id: 'A', text: 'Joule' }, { id: 'B', text: 'Watt' }, { id: 'C', text: 'Newton' }, { id: 'D', text: 'Pascal' }], correctOptionId: 'C', explanation: 'La force se mesure en Newton (N). 1 N = la force pour accélérer 1 kg de 1 m/s².', difficulty: 1, xpReward: 10 },
  { id: 'mec-03', subject: 'mecanique', emoji: '🎡', question: 'Qu\'est-ce qu\'une machine simple ?', options: [{ id: 'A', text: 'Un ordinateur basique' }, { id: 'B', text: 'Un outil qui transforme ou transmet une force' }, { id: 'C', text: 'Une machine à vapeur' }, { id: 'D', text: 'Un robot' }], correctOptionId: 'B', explanation: 'Machines simples : levier, roue, poulie, plan incliné, coin, vis. Elles multiplient l\'effet d\'une force.', difficulty: 2, xpReward: 15 },
  { id: 'mec-04', subject: 'mecanique', emoji: '🚗', question: 'Si une voiture roule à 100 km/h pendant 2 h, quelle distance parcourt-elle ?', options: [{ id: 'A', text: '50 km' }, { id: 'B', text: '100 km' }, { id: 'C', text: '150 km' }, { id: 'D', text: '200 km' }], correctOptionId: 'D', explanation: 'Distance = vitesse × temps = 100 × 2 = 200 km.', difficulty: 1, xpReward: 10 },
  { id: 'mec-05', subject: 'mecanique', emoji: '⚖️', question: 'Qu\'est-ce que la friction (frottement) ?', options: [{ id: 'A', text: 'Une force qui accélère les objets' }, { id: 'B', text: 'Une force qui s\'oppose au mouvement' }, { id: 'C', text: 'La masse d\'un objet' }, { id: 'D', text: 'La vitesse d\'un objet' }], correctOptionId: 'B', explanation: 'Le frottement est une force qui s\'oppose au glissement de deux surfaces l\'une contre l\'autre.', difficulty: 1, xpReward: 10 },
  { id: 'mec-06', subject: 'mecanique', emoji: '🔩', question: 'Quel principe explique que "pour chaque action, il y a une réaction égale et opposée" ?', options: [{ id: 'A', text: '1ère loi de Newton' }, { id: 'B', text: '2ème loi de Newton' }, { id: 'C', text: '3ème loi de Newton' }, { id: 'D', text: 'Loi d\'Archimède' }], correctOptionId: 'C', explanation: 'La 3ème loi de Newton (action-réaction) : si tu pousses un mur, le mur te pousse en retour !', difficulty: 2, xpReward: 15 },
  { id: 'mec-07', subject: 'mecanique', emoji: '🏋️', question: 'Un levier sert à quoi ?', options: [{ id: 'A', text: 'Mesurer la température' }, { id: 'B', text: 'Soulever un objet lourd avec moins d\'effort' }, { id: 'C', text: 'Calculer la vitesse' }, { id: 'D', text: 'Produire de l\'électricité' }], correctOptionId: 'B', explanation: 'Un levier (comme une pelle ou un pied-de-biche) permet de soulever de lourdes charges avec un effort réduit.', difficulty: 1, xpReward: 10 },
  { id: 'mec-08', subject: 'mecanique', emoji: '🌍', question: 'Quelle est la valeur approximative de la gravité terrestre (g) ?', options: [{ id: 'A', text: '1 m/s²' }, { id: 'B', text: '9,8 m/s²' }, { id: 'C', text: '100 m/s²' }, { id: 'D', text: '0,1 m/s²' }], correctOptionId: 'B', explanation: 'g ≈ 9,8 m/s² sur Terre. Sur la Lune, g ≈ 1,6 m/s² (6× plus faible).', difficulty: 2, xpReward: 15 },
];

export default Q;
