import type { QuizQuestion } from '@/types';

const Q: QuizQuestion[] = [
  { id: 'met-01', subject: 'meteo', emoji: '🌧️', question: 'Quelle est la différence entre la pluie et la bruine ?', options: [{ id: 'A', text: 'La pluie est plus froide' }, { id: 'B', text: 'La bruine a de plus fines gouttelettes' }, { id: 'C', text: 'La bruine tombe plus vite' }, { id: 'D', text: 'Aucune différence' }], correctOptionId: 'B', explanation: 'La bruine a des gouttelettes très fines (< 0.5 mm), la pluie a de plus grosses gouttes.', difficulty: 2, xpReward: 15 },
  { id: 'met-02', subject: 'meteo', emoji: '⛈️', question: 'Qu\'est-ce qui provoque le tonnerre ?', options: [{ id: 'A', text: 'Les nuages qui se heurtent' }, { id: 'B', text: 'La foudre qui chauffe l\'air brusquement' }, { id: 'C', text: 'Le vent violent' }, { id: 'D', text: 'La pluie qui tombe fort' }], correctOptionId: 'B', explanation: 'L\'arc électrique de la foudre chauffe l\'air à 30 000 °C, créant une onde de choc sonore.', difficulty: 2, xpReward: 15 },
  { id: 'met-03', subject: 'meteo', emoji: '🌈', question: 'Comment se forme un arc-en-ciel ?', options: [{ id: 'A', text: 'La lumière traverse la pluie et se décompose' }, { id: 'B', text: 'Les nuages colorent la lumière' }, { id: 'C', text: 'Le Soleil change de couleur' }, { id: 'D', text: 'La chaleur colore l\'air' }], correctOptionId: 'A', explanation: 'Les gouttes d\'eau agissent comme des prismes et décomposent la lumière blanche.', difficulty: 1, xpReward: 10 },
  { id: 'met-04', subject: 'meteo', emoji: '🌀', question: 'Quel phénomène météo est caractérisé par un vent en spirale très fort ?', options: [{ id: 'A', text: 'La brise' }, { id: 'B', text: 'L\'anticyclone' }, { id: 'C', text: 'La tornade' }, { id: 'D', text: 'Le brouillard' }], correctOptionId: 'C', explanation: 'La tornade est un vortex de vent violent qui peut dépasser 500 km/h.', difficulty: 1, xpReward: 10 },
  { id: 'met-05', subject: 'meteo', emoji: '❄️', question: 'À quelle température l\'eau gèle-t-elle ?', options: [{ id: 'A', text: '-10°C' }, { id: 'B', text: '0°C' }, { id: 'C', text: '4°C' }, { id: 'D', text: '10°C' }], correctOptionId: 'B', explanation: 'L\'eau pure gèle à 0°C sous pression atmosphérique normale.', difficulty: 1, xpReward: 10 },
  { id: 'met-06', subject: 'meteo', emoji: '🌡️', question: 'Quelle est l\'unité de mesure de la pression atmosphérique ?', options: [{ id: 'A', text: 'Pascal / hPa' }, { id: 'B', text: 'Newton' }, { id: 'C', text: 'Kelvin' }, { id: 'D', text: 'Joule' }], correctOptionId: 'A', explanation: 'La pression atmosphérique se mesure en hectopascals (hPa). La pression standard est 1013 hPa.', difficulty: 2, xpReward: 15 },
  { id: 'met-07', subject: 'meteo', emoji: '💨', question: 'Quel instrument mesure la vitesse du vent ?', options: [{ id: 'A', text: 'Baromètre' }, { id: 'B', text: 'Thermomètre' }, { id: 'C', text: 'Anémomètre' }, { id: 'D', text: 'Hygromètre' }], correctOptionId: 'C', explanation: 'L\'anémomètre mesure la vitesse du vent (en km/h ou nœuds).', difficulty: 2, xpReward: 15 },
  { id: 'met-08', subject: 'meteo', emoji: '☁️', question: 'Comment appelle-t-on les nuages très haut dans le ciel, blancs et fins comme des fils ?', options: [{ id: 'A', text: 'Cumulus' }, { id: 'B', text: 'Stratus' }, { id: 'C', text: 'Cirrus' }, { id: 'D', text: 'Nimbus' }], correctOptionId: 'C', explanation: 'Les cirrus sont de fins nuages de glace à haute altitude (> 6 000 m).', difficulty: 2, xpReward: 15 },
];

export default Q;
