import type { QuizQuestion } from '@/types';

const Q: QuizQuestion[] = [
  { id: 'tel-01', subject: 'telecom', emoji: '📡', question: 'Que signifie "Wi-Fi" ?', options: [{ id: 'A', text: 'Wireless Fidelity' }, { id: 'B', text: 'Wide Frequency' }, { id: 'C', text: 'Web Interface' }, { id: 'D', text: 'Wireless File' }], correctOptionId: 'A', explanation: 'Wi-Fi = Wireless Fidelity. C\'est une norme de réseau sans fil (IEEE 802.11).', difficulty: 2, xpReward: 15 },
  { id: 'tel-02', subject: 'telecom', emoji: '📱', question: 'Que signifie "5G" dans les réseaux mobiles ?', options: [{ id: 'A', text: '5 Gigaoctets' }, { id: 'B', text: '5ème génération de réseau mobile' }, { id: 'C', text: '5 GHz' }, { id: 'D', text: '5 Gigas de données' }], correctOptionId: 'B', explanation: 'La 5G est la 5ème génération de réseau mobile, 10× plus rapide que la 4G.', difficulty: 1, xpReward: 10 },
  { id: 'tel-03', subject: 'telecom', emoji: '🌐', question: 'Quelle technologie utilise la lumière pour transmettre des données très rapidement ?', options: [{ id: 'A', text: 'Câble coaxial' }, { id: 'B', text: 'Fibre optique' }, { id: 'C', text: 'Câble cuivre' }, { id: 'D', text: 'Bluetooth' }], correctOptionId: 'B', explanation: 'La fibre optique transmet des données sous forme de lumière, à des débits de plusieurs Gbps.', difficulty: 2, xpReward: 15 },
  { id: 'tel-04', subject: 'telecom', emoji: '📻', question: 'Comment les ondes radio se propagent-elles ?', options: [{ id: 'A', text: 'Uniquement dans l\'eau' }, { id: 'B', text: 'Dans le vide et dans l\'air, à la vitesse de la lumière' }, { id: 'C', text: 'Uniquement dans les fils' }, { id: 'D', text: 'Plus lentement que le son' }], correctOptionId: 'B', explanation: 'Les ondes radio sont des ondes électromagnétiques : elles se propagent à 300 000 km/s même dans le vide.', difficulty: 2, xpReward: 15 },
  { id: 'tel-05', subject: 'telecom', emoji: '🔵', question: 'À quelle distance maximale fonctionne le Bluetooth classique ?', options: [{ id: 'A', text: '1 m' }, { id: 'B', text: '10 m' }, { id: 'C', text: '100 m' }, { id: 'D', text: '1 km' }], correctOptionId: 'B', explanation: 'Le Bluetooth fonctionne typiquement sur 10 m. Bluetooth 5.0 peut aller jusqu\'à 100 m.', difficulty: 2, xpReward: 15 },
  { id: 'tel-06', subject: 'telecom', emoji: '🛰️', question: 'À quoi servent les satellites de communication ?', options: [{ id: 'A', text: 'Observer les étoiles' }, { id: 'B', text: 'Relayer des signaux sur de longues distances' }, { id: 'C', text: 'Produire de l\'électricité' }, { id: 'D', text: 'Prévoir la météo uniquement' }], correctOptionId: 'B', explanation: 'Les satellites relaient TV, téléphone, internet entre des points très éloignés sur Terre.', difficulty: 1, xpReward: 10 },
  { id: 'tel-07', subject: 'telecom', emoji: '📞', question: 'Quelle technologie permet de passer des appels via Internet ?', options: [{ id: 'A', text: 'SMS' }, { id: 'B', text: 'VoIP' }, { id: 'C', text: 'GSM' }, { id: 'D', text: 'FM' }], correctOptionId: 'B', explanation: 'VoIP (Voice over IP) permet les appels via Internet. Exemples : WhatsApp, Zoom, Teams.', difficulty: 2, xpReward: 15 },
  { id: 'tel-08', subject: 'telecom', emoji: '🔐', question: 'Que fait le chiffrement (cryptage) des données ?', options: [{ id: 'A', text: 'Accélère la connexion' }, { id: 'B', text: 'Compresse les fichiers' }, { id: 'C', text: 'Rend les données illisibles sans clé' }, { id: 'D', text: 'Efface les données' }], correctOptionId: 'C', explanation: 'Le chiffrement encode les données : seul celui qui a la clé peut les lire. C\'est le "S" de HTTPS.', difficulty: 2, xpReward: 15 },
];

export default Q;
