import type { DbReleaseNote } from '@/lib/db';

// Historique statique — fallback si Supabase non configuré
export const STATIC_RELEASE_NOTES: DbReleaseNote[] = [
  {
    id: 'static-v0.4.0',
    version: '0.4.0',
    deployed_at: '2026-05-31T18:00:00Z',
    title: 'Admin questions + espace parent amélioré + bug niveau',
    summary: 'Interface admin pour modifier/supprimer les questions importées, espace parent avec édition des élèves et affichage de leur progression, correction du bug niveau mismatch.',
    changes: [
      'Bug fix : niveau mismatch Mohamed — activeProfileId stale nettoyé au chargement de l\'accueil',
      'Admin /admin/questions : liste les questions importées (DB), filtre par matière',
      'Admin /admin/questions/[id] : formulaire complet d\'édition (question, options, explication, difficulté)',
      'API PUT /api/questions/[id] : mise à jour question (protégée service role key)',
      'API DELETE /api/questions/[id] : suppression question (protégée)',
      'API GET /api/questions : liste questions DB avec filtre subject',
      'Admin layout avec nav partagée (Import CSV · Questions)',
      'Parent : bouton ✏️ sur chaque élève pour modifier prénom/âge/classe inline',
      'Parent : badge XP/niveau affiché sur chaque carte élève (depuis localStorage)',
      'Composant StudentCard extrait (src/components/parent/)',
    ],
    tags: ['feature', 'bugfix', 'admin'],
    deployed_by: 'Claude Code',
  },
  {
    id: 'static-v0.3.0',
    version: '0.3.0',
    deployed_at: '2026-05-31T12:00:00Z',
    title: 'Sablier, bugs corrigés, espace parent',
    summary: 'Sablier 30s par question avec XP décroissants, 3 bugs corrigés, lien vers l\'historique des versions, inscription parent par email avec gestion des élèves.',
    changes: [
      'Sablier 30s par question (cercle SVG animé, vert→orange→rouge)',
      'XP gagnables décroissants : -70% si temps plein, minimum 30% du XP de base',
      'Auto-soumission mauvaise réponse à l\'expiration du temps',
      'Bug fix : "Rejouer" ne montre plus "Matière introuvable" (correction selectQuestions SRS)',
      'Bug fix : questions en état "review" (répondues, pas encore dues) sélectionnées en fallback',
      'Bug fix : XP et niveau toujours affichés (même à 0) sur la page d\'accueil',
      'Lien "Versions" et "Espace parent" sur la page d\'accueil',
      'Page /auth : inscription et connexion parent par email/mot de passe',
      'Page /parent : ajout, visualisation et suppression d\'élèves',
      'Page d\'accueil dynamique : si parent connecté, affiche ses élèves Supabase',
      'Migration SQL 007 : table students avec RLS',
    ],
    tags: ['feature', 'bugfix'],
    deployed_by: 'Claude Code',
  },
  {
    id: 'static-v0.2.0',
    version: '0.2.0',
    deployed_at: '2026-05-31T00:00:00Z',
    title: 'Import CSV + 4 niveaux de difficulté + Release Notes',
    summary: 'Système d\'import de questions via CSV ou API, 4 niveaux de difficulté (Initié → Gourou), versions assistée/avancée par question, page de release notes.',
    changes: [
      'Import questions via CSV (POST /api/questions/import)',
      '4 niveaux de difficulté : Initié 🌱, Apprenti 📖, Expert ⚡, Gourou 🔥',
      'Champ questionAssisted + explanationAssisted + textAssisted par option',
      'Champ imageUrl optionnel par question',
      'Champ category optionnel par question',
      'Table Supabase questions pour les questions importées',
      'Page admin /admin/import avec dropzone CSV',
      'Système de release notes (table + page /releases + script npm run release)',
      'CLAUDE.md : index des .md + règles de versionnement SemVer',
    ],
    tags: ['feature', 'admin', 'docs'],
    deployed_by: 'Claude Code',
  },
  {
    id: 'static-v0.1.0',
    version: '0.1.0',
    deployed_at: '2026-05-30T00:00:00Z',
    title: 'Initial Release — Sons, Score, Mohamed, Quiz',
    summary: 'Premier déploiement avec les trois profils actifs : Omar (quiz), Esma (mots illustrés), Mohamed (clavier/mots/sciences).',
    changes: [
      'Quiz interactif par matière (maths, français, SVT, histoire, physique + 9 autres)',
      'Spaced repetition (algorithme SM-2) pour Omar',
      'Sons enthousiastes (Web Audio API + SpeechSynthesis)',
      'XpGainToast : badge "+N XP" flottant animé',
      'Mohamed — 3 modes : LetterMode, WordMode, ScienceMode',
      'Esma — mots illustrés FR/EN/ES avec TTS',
      'Sélecteur d\'avatar (6 avatars, déblocage XP)',
      'Score + badges + streak (localStorage + sync Supabase)',
      '50 tests Jest + e2e Playwright',
    ],
    tags: ['feature'],
    deployed_by: 'Claude Code',
  },
];
