/** Public API of the competition module: rankings by centre (pseudonyms), weekly challenge, automatic medals. */
export { isoWeek, previousWeek, isWeek } from './domain/week';
export type { NicknameResult, NameResult, RealNames } from './domain/nickname';
export { validateNickname, validatePersonName, generateNickname } from './domain/nickname';
export type { LearnerIdentity, IdentityUpdate, IdentityUpdateResult } from './domain/identity';
export { validateIdentityUpdate, isIdentityReady, canPrintDiploma } from './domain/identity';
export type { RankMetric, BoardRow, RankedRow, WeeklyResult, RankedResult, Award } from './domain/ranking';
export { rankBy, rankWeekly, awardsFor, MEDALS, AWARD_MIN_CORRECT } from './domain/ranking';
export type { WeeklyChallenge, ChallengeAnswer } from './application/challenge';
export { challengeFor, scoreChallenge, CHALLENGE_LENGTH } from './application/challenge';
export type { CompetitionData, CompetitionView } from './application/view';
export { buildCompetitionView, pastAwardsOf } from './application/view';
export type { TeacherAward } from './infra/competition-client';
export type { ProfileIdentity } from './infra/competition-client';
export type { FeedEvent } from './infra/competition-client';
export { fetchPair, claimPairBonus, fetchFeed, sendCheer, hideFeedEvent, fetchIdentity, saveIdentity, fetchCompetition, updateRankingSettings, fetchTeacherAwards, revokeAwardRequest } from './infra/competition-client';
export { CompetitionPanel } from './ui/CompetitionPanel';
export { IdentityForm } from './ui/IdentityForm';
export type { Group } from './domain/pairs';
export { pairsFor, groupOf } from './domain/pairs';
export type { ChallengeScore, BonusStatus, BonusMember } from './domain/bonus';
export { bonusStatus, BONUS_XP, MENTION_MIN_CORRECT } from './domain/bonus';
export type { FeedEventInfo } from './domain/feed';
export { describeEvent, canCheer } from './domain/feed';
export type { PairData, PairView } from './application/pair-view';
export { buildPairView, groupsOfWeek } from './application/pair-view';
export { PairCard } from './ui/PairCard';
export { ActivityFeed } from './ui/ActivityFeed';
